import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home() {    
  return (
    <>
      <Head>
        <title>Login - Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./Instagram_icon.ico" />
      </Head>
      <main className={`${styles.main}`}>
       <div className='container'>

        <div className="login-container">
          <h1>Instagram</h1>
          <input type="text" class="form-input" placeholder="Phone number, username, or email"/>
          <input type="password" class="form-input" placeholder="Password"/>
          <br></br>
          <button className="btn">Log in</button>
        </div>

        <div className="or">OR</div>
        
        
      </div>
        
      </main>
    </>
  )
}
